[theme]
inherit = basic
html5_doctype = true
stylesheet = stylesheets/theme.css
pygments_style = none
sidebars =

[options]
site_author =
site_description =

palette_primary = blue
palette_accent = blue

language_direction = ltr

logo = images/obi-logo.svg
logo_icon =
logo_url = https://www.openbraininstitute.org/
favicon = https://www.openbraininstitute.org/favicon.ico

repo_url =
repo_path =
repo_name =
repo_icon =

feature_tabs =

use_google_fonts =
font_text =
font_code =

font_header =

title_prefix =

social_title = Follow the Open Brain Institute
social =
    linkedin-square, https://www.linkedin.com/company/openbraininstitute/
    twitter-square, https://x.com/OpenBrainInst
    youtube, https://www.youtube.com/@openbraininstitute
    cloud, https://bsky.app/profile/openbraininst.bsky.social

manifest =

company = Open Brain Institute
address =
    Avenue du Tribunal-Fédéral 34
    Lausanne, Vaud 1005, CH

legal =

use_original_style =

metadata_file =
metadata_distribution =
metadata_overrides =
